modLoader="javafml" #mandatory The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
loaderVersion="[35,)" #mandatory A version range to match for said mod loader - for regular FML @Mod it will be the forge version
license="All rights reserved" #mandatory The license for you mod. Review your options at https://choosealicense.com/.
# issueTrackerURL="http://my.issue.tracker/" #optional A URL to refer people to when problems occur with this mod
[[mods]] #mandatory A list of mods - how many allowed here is determined by the individual mod loader
modId="example_mod" #mandatory The modid of the mod
version="${file.jarVersion}" #mandatory The version number of the mod, ${file.jarVersion} will substitute the value of the Implementation-Version
displayName="Example Mod" #mandatory A display name for the mod
# updateJSONURL="http://myurl.me/" #optional A URL to query for updates for this mod. See the JSON update specification <here>
# displayURL="http://example.com/" #optional A URL for the "homepage" for this mod, displayed in the mod UI
# logoFile="examplemod.png" #optional A file name (in the root of the mod JAR) containing a logo for display
credits="MinecraftForge Team" #optional A text field displayed in the mod UI
authors="Love, Cheese and small house plants" #optional A text field displayed in the mod UI
description='''
This is a long form description of the mod. You can write whatever you want here

Have some lorem ipsum.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed mollis lacinia magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed sagittis luctus odio eu tempus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque volutpat ligula eget lacus auctor sagittis. In hac habitasse platea dictumst. Nunc gravida elit vitae sem vehicula efficitur. Donec mattis ipsum et arcu lobortis, eleifend sagittis sem rutrum. Cras pharetra quam eget posuere fermentum. Sed id tincidunt justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
''' #mandatory The description text for the mod (multi line!)
[[dependencies.example_mod]] #optional A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
    modId="forge" #mandatory The modid of the dependency
    mandatory=true #mandatory Does this dependency have to exist - if not, ordering below must be specified
    versionRange="[35,)" #mandatory The version range of the dependency
    ordering="NONE" # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    side="BOTH"  # Side this dependency is applied on - BOTH, CLIENT or SERVER
[[dependencies.example_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)" # This range declares a minimum of the current minecraft version up to but not including the next major version
    ordering="NONE"
    side="BOTH"
